In [52]:
#Setup of api and of folder where data is being stored 
import os 
import fastf1

os.makedirs('cache', exist_ok=True)
fastf1.Cache.enable_cache('cache')

In [53]:
#Just a test to see if everything works 
my_session = fastf1.get_session(2025, 'Australian Grand Prix', 'Q')
my_session.load ()

core           INFO 	Loading data for Australian Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '4'
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '81', '1', '63', '22', '23', '16', '44', '10', '55', '6', '14', '18', '7', '5', '12', '27', '30', '31', '87']

In [54]:
my_laps = my_session.laps
my_laps.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:16:54.443000,NOR,4,0 days 00:01:50.421000,1.0,1.0,0 days 00:15:08.068000,NaT,0 days 00:00:48.877000,0 days 00:00:24.492000,...,True,McLaren,0 days 00:15:08.068000,2025-03-15 05:02:39.667,1,NaN,False,,False,False
1,0 days 00:18:10.446000,NOR,4,0 days 00:01:16.003000,2.0,1.0,NaT,NaT,0 days 00:00:26.383000,0 days 00:00:17.285000,...,True,McLaren,0 days 00:16:54.443000,2025-03-15 05:04:26.042,1,NaN,False,,False,True
2,0 days 00:20:12.796000,NOR,4,0 days 00:02:02.350000,3.0,1.0,NaT,0 days 00:19:55.246000,0 days 00:00:37.180000,0 days 00:00:23.115000,...,True,McLaren,0 days 00:18:10.446000,2025-03-15 05:05:42.045,1,NaN,False,,False,False
3,0 days 00:22:09.056000,NOR,4,0 days 00:01:56.260000,4.0,2.0,0 days 00:20:16.711000,NaT,0 days 00:00:52.032000,0 days 00:00:23.199000,...,False,McLaren,0 days 00:20:12.796000,2025-03-15 05:07:44.395,1,NaN,False,,False,False
4,0 days 00:23:24.968000,NOR,4,0 days 00:01:15.912000,5.0,2.0,NaT,NaT,0 days 00:00:26.463000,0 days 00:00:17.116000,...,False,McLaren,0 days 00:22:09.056000,2025-03-15 05:09:40.655,1,NaN,False,,False,True

In [55]:
my_session.results[['Abbreviation', 'FullName']] #Just to make sure the correct abbreviations are being used later on

   Abbreviation               FullName
4           NOR           Lando Norris
81          PIA          Oscar Piastri
1           VER         Max Verstappen
63          RUS         George Russell
22          TSU           Yuki Tsunoda
23          ALB        Alexander Albon
16          LEC        Charles Leclerc
44          HAM         Lewis Hamilton
10          GAS           Pierre Gasly
55          SAI           Carlos Sainz
6           HAD           Isack Hadjar
14          ALO        Fernando Alonso
18          STR           Lance Stroll
7           DOO            Jack Doohan
5           BOR      Gabriel Bortoleto
12          ANT  Andrea Kimi Antonelli
27          HUL        Nico Hulkenberg
30          LAW            Liam Lawson
31          OCO           Esteban Ocon
87          BEA         Oliver Bearman

In [56]:
my_laps_AntvsRus = my_laps.pick_drivers(['ANT','RUS'])
my_laps_AntvsRus

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
55,0 days 00:14:31.889000,RUS,63,NaT,1.0,1.0,0 days 00:12:48.719000,NaT,NaT,0 days 00:00:19.626000,...,True,Mercedes,0 days 00:12:48.719000,2025-03-15 05:00:20.318,1,NaN,False,,False,False
56,0 days 00:15:49.099000,RUS,63,0 days 00:01:17.210000,2.0,1.0,NaT,NaT,0 days 00:00:26.777000,0 days 00:00:17.431000,...,True,Mercedes,0 days 00:14:31.889000,2025-03-15 05:02:03.488,1,NaN,False,,False,True
57,0 days 00:18:40.738000,RUS,63,NaT,3.0,1.0,NaT,0 days 00:17:29.191000,0 days 00:00:35.312000,0 days 00:00:21.941000,...,True,Mercedes,0 days 00:15:49.099000,2025-03-15 05:03:20.698,1,NaN,False,,False,False
58,0 days 00:20:40.835000,RUS,63,0 days 00:02:00.097000,4.0,2.0,0 days 00:18:45.111000,NaT,0 days 00:00:51.163000,0 days 00:00:21.857000,...,False,Mercedes,0 days 00:18:40.738000,2025-03-15 05:06:12.337,1,NaN,False,,False,False
59,0 days 00:21:57.130000,RUS,63,0 days 00:01:16.295000,5.0,2.0,NaT,NaT,0 days 00:00:26.416000,0 days 00:00:17.163000,...,False,Mercedes,0 days 00:20:40.835000,2025-03-15 05:08:12.434,1,NaN,False,,False,True
60,0 days 00:25:57.755000,RUS,63,NaT,6.0,2.0,NaT,0 days 00:23:22.804000,0 days 00:00:30.091000,0 days 00:00:19.251000,...,False,Mercedes,0 days 00:21:57.130000,2025-03-15 05:09:28.729,12,NaN,False,,False,False
61,0 days 00:27:50.813000,RUS,63,0 days 00:01:53.058000,7.0,3.0,0 days 00:26:02.403000,NaT,0 days 00:00:46.247000,0 days 00:00:21.151000,...,True,Mercedes,0 days 00:25:57.755000,2025-03-15 05:13:29.354,1,NaN,False,,False,False
62,0 days 00:29:06.784000,RUS,63,0 days 00:01:15.971000,8.0,3.0,NaT,NaT,0 days 00:00:26.366000,0 days 00:00:17.086000,...,True,Mercedes,0 days 00:27:50.813000,2025-03-15 05:15:22.412,1,NaN,False,,False,True
63,0 days 00:38:22.074000,RUS,63,NaT,9.0,3.0,NaT,0 days 00:30:54.216000,0 days 00:00:38.623000,0 days 00:00:26.643000,...,True,Mercedes,0 days 00:29:06.784000,2025-03-15 05:16:38.383,12,NaN,False,,False,False
64,0 days 00:40:13.260000,RUS,63,0 days 00:01:51.186000,10.0,4.0,0 days 00:38:24.907000,NaT,0 days 00:00:47.112000,0 days 00:00:22.713000,...,False,Mercedes,0 days 00:38:22.074000,2025-03-15 05:25:53.673,1,NaN,False,,False,False
65,0 days 00:41:29.058000,RUS,63,0 days 00:01:15.798000,11.0,4.0,NaT,NaT,0 days 00:00:26.373000,0 days 00:00:17.128000,...,False,Mercedes,0 days 00:40:13.260000,2025-03-15 05:27:44.859,1,NaN,False,,False,True
66,0 days 00:48:36.703000,RUS,63,NaT,12.0,4.0,NaT,0 days 00:42:58.848000,0 days 00:00:33.010000,0 days 00:00:19.701000,...,False,Mercedes,0 days 00:41:29.058000,2025-03-15 05:29:00.657,1,NaN,False,,False,False
67,0 days 00:50:55.079000,RUS,63,0 days 00:02:18.376000,13.0,5.0,0 days 00:48:44.877000,NaT,0 days 00:01:05.021000,0 days 00:00:21.689000,...,True,Mercedes,0 days 00:48:36.703000,2025-03-15 05:36:08.302,1,NaN,False,,False,False
68,0 days 00:52:17.258000,RUS,63,0 days 00:01:22.179000,14.0,5.0,NaT,NaT,0 days 00:00:26.183000,0 days 00:00:17.028000,...,True,Mercedes,0 days 00:50:55.079000,2025-03-15 05:38:26.678,12,NaN,False,,False,True
69,0 days 01:00:47.401000,RUS,63,NaT,15.0,5.0,NaT,0 days 00:53:55.598000,0 days 00:00:38.250000,0 days 00:00:20.215000,...,True,Mercedes,0 days 00:52:17.258000,2025-03-15 05:39:48.857,12,NaN,False,,False,False
70,0 days 01:02:47.729000,RUS,63,0 days 00:02:00.328000,16.0,6.0,0 days 01:00:56.417000,NaT,0 days 00:00:55.153000,0 days 00:00:20.940000,...,True,Mercedes,0 days 01:00:47.401000,2025-03-15 05:48:19.000,1,NaN,False,,False,False
71,0 days 01:04:03.424000,RUS,63,0 days 00:01:15.695000,17.0,6.0,NaT,NaT,0 days 00:00:26.104000,0 days 00:00:17.030000,...,True,Mercedes,0 days 01:02:47.729000,2025-03-15 05:50:19.328,1,NaN,False,,False,True
72,0 days 01:08:41.270000,RUS,63,NaT,18.0,6.0,NaT,0 days 01:05:36.954000,0 days 00:00:35.357000,0 days 00:00:19.936000,...,True,Mercedes,0 days 01:04:03.424000,2025-03-15 05:51:35.023,1,NaN,False,,False,False
73,0 days 01:10:41.176000,RUS,63,0 days 00:01:59.906000,19.0,7.0,0 days 01:08:48.754000,NaT,0 days 00:00:55.203000,0 days 00:00:22.409000,...,True,Mercedes,0 days 01:08:41.270000,2025-03-15 05:56:12.869,1,NaN,False,,False,False
74,0 days 01:11:56.722000,RUS,63,0 days 00:01:15.546000,20.0,7.0,NaT,NaT,0 days 00:00:26.163000,0 days 00:00:16.951000,...,True,Mercedes,0 days 01:10:41.176000,2025-03-15 05:58:12.775,1,NaN,False,,False,True
262,0 days 00:16:20.540000,ANT,12,0 days 00:02:04.708000,1.0,1.0,0 days 00:14:25.084000,NaT,0 days 00:01:00.679000,0 days 00:00:22.375000,...,True,Mercedes,0 days 00:14:25.084000,2025-03-15 05:01:56.683,1,NaN,False,,False,False
263,0 days 00:17:37.989000,ANT,12,0 days 00:01:17.449000,2.0,1.0,NaT,NaT,0 days 00:00:26.892000,0 days 00:00:17.476000,...,True,Mercedes,0 days 00:16:20.540000,2025-03-15 05:03:52.139,1,NaN,False,,False,True
264,0 days 00:21:51.896000,ANT,12,NaT,3.0,1.0,NaT,0 days 00:19:21.389000,0 days 00:00:40.633000,0 days 00:00:23.383000,...,True,Mercedes,0 days 00:17:37.989000,2025-03-15 05:05:09.588,1,NaN,False,,False,False
265,0 days 00:23:40.149000,ANT,12,0 days 00:01:48.253000,4.0,2.0,0 days 00:21:53.945000,NaT,0 days 00:00:43.523000,0 days 00:00:22.310000,...,True,Mercedes,0 days 00:21:51.896000,2025-03-15 05:09:23.495,1,NaN,False,,False,False
266,0 days 00:24:56.915000,ANT,12,0 days 00:01:16.766000,5.0,2.0,NaT,NaT,0 days 00:00:26.585000,0 days 00:00:17.427000,...,True,Mercedes,0 days 00:23:40.149000,2025-03-15 05:11:11.748,12,NaN,False,,False,True
267,0 days 00:26:43.987000,ANT,12,0 days 00:01:47.072000,6.0,2.0,NaT,NaT,0 days 00:00:40.940000,0 days 00:00:21.775000,...,True,Mercedes,0 days 00:24:56.915000,2025-03-15 05:12:28.514,1,NaN,False,,False,True
268,0 days 00:28:28.449000,ANT,12,0 days 00:01:44.462000,7.0,2.0,NaT,NaT,0 days 00:00:39.073000,0 days 00:00:22.117000,...,True,Mercedes,0 days 00:26:43.987000,2025-03-15 05:14:15.586,1,NaN,False,,False,True
269,0 days 00:29:44.974000,ANT,12,0 days 00:01:16.525000,8.0,2.0,NaT,NaT,0 days 00:00:26.443000,0 days 00:00:17.166000,...,True,Mercedes,0 days 00:28:28.449000,2025-03-15 05:16:00.048,1,NaN,False,,False,True
270,0 days 00:31:25.314000,ANT,12,NaT,9.0,2.0,NaT,0 days 00:31:25.314000,0 days 00:00:33.919000,0 days 00:00:22.375000,...,True,Mercedes,0 days 00:29:44.974000,2025-03-15 05:17:16.573,1,NaN,False,,False,False

In [57]:
my_antonelli_fastestlap = my_laps_AntvsRus.pick_drivers('ANT').pick_fastest()
my_russell_fastestlap = my_laps_AntvsRus.pick_drivers('RUS').pick_fastest()

print(my_antonelli_fastestlap[['Driver','LapTime']])
print(my_russell_fastestlap[['Driver','LapTime']])

Driver                        ANT
LapTime    0 days 00:01:16.525000
dtype: object
Driver                        RUS
LapTime    0 days 00:01:15.546000
dtype: object

In [58]:
my_gap = my_antonelli_fastestlap['LapTime'] - my_russell_fastestlap['LapTime']
my_gap

Timedelta('0 days 00:00:00.979000')